### ISSUE TITLE
General markup guidelines, table example

### ISSUE THREAD

**Issue by objectfoo** [CaleyD/FrontEndGuidelines#2]
I don't think the scope attribute is needed when the header applies to a column. No scope attribute means 'auto', it looks like this means the scope is a single column.

Check this example: at [W3C](http://www.w3.org/TR/2011/WD-html5-author-20110809/the-th-element.html#attr-th-scope-auto) the row headers have scope but the columns don't.

Although I don't know what this will mean to jaws

**Comment by CaleyD** [comment]
I thought you're object foo? What is this stargazer/satake?
